name: Release

on:
  push:
    tags:
      - '*'

jobs:
  npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version: lts/*

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Update npm
        run: npm install -g npm@latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Publish to npm
        run: npm publish --provenance --no-git-checks --access public

  jsr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Publish to JSR
        run: bunx pkg-to-jsr && bunx jsr publish
        env:
          JSR_TOKEN: ${{ secrets.JSR_TOKEN }}

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: [npm, jsr]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Generate changelog
        run: bun x changelogithub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
