# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Deno Update

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch: {}

env:
  DENO_VERSION: 2.x

jobs:
  update:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Deno
        uses: denoland/setup-deno@11b63cf76cfcafb4e43f97b6cad24d8e8438f62d # v1.5.2
        with:
          deno-version: ${{ env.DENO_VERSION }}

      - name: Update dependencies with molt
        id: run-deno-molt
        env:
          NO_COLOR: true
        run: |
          {
            echo 'MOLT_RESULT<<EOF'
            deno run --allow-all jsr:@molt/cli --write $(find . -type f -name '*.mts' -o -name '*.cts' -o -name '*.mjs' -o -name '*.cjs' -o -name '*.ts' -o -name '*.js' -o -name '*.tsx' -o -name '*.jsx')
            echo EOF
          } >> $GITHUB_OUTPUT

      - name: Check
        run: deno task check

      - name: Run linter
        run: deno task lint

      - name: Create pull request
        uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c # v6.1.0
        with:
          commit-message: 'chore(deps): Update deno dependencies'
          title: Update Deno dependencies
          body: |-
            Some external modules are stale.
            <details><summary>Details</summary><div>

            ```
            ${{ steps.run-deno-molt.outputs.MOLT_RESULT }}
            ```

            </div></details>
          branch: molt-update
          author: GitHub <noreply@github.com>
          delete-branch: true
